---
# tasks file for zee-balancer
- name: Install haproxy
  dnf:
    name: 
      - haproxy
      - firewalld
    state: present

- name: Configure haproxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg

- name: Create /run/haproxy
  file:
    path: /run/haproxy
    state: directory
    owner: haproxy
    group: haproxy
    mode: 755

- name: Enable and start haproxy
  service:
    name: "{{item}}"
    state: started
    enabled: yes
  loop:
    - haproxy
    - firewalld

- name: Add Firewall Rule
  firewalld:
    service: http
    state: enabled
    immediate: yes
    permanent: yes
